name: Weekly Milestones

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Schedule Milestones
        uses: readmeio/scheduled-milestones@v1.1
        id: scheduled
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Up for Review
          days: Tuesday,Thursday
          date_options: '{"month": "long", "day": "numeric"}'

      - name: Created Milestones
        run: echo ${{ steps.scheduled.outputs.milestones }}