name: JUnit Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Setup Maven
      uses: nanovms/setup-maven@v1
      with:
        distribution: 'apache'
        maven-version: '3.8.3'

    - name: Build with Maven
      run: mvn clean compile

    - name: Run JUnit Tests
      run: mvn test