name: Building project

on:
  push:
    branches: [ tests2_feature_java1.8 ]
  pull_request:
    branches: [ tests2_feature_java1.8 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: '12'

    - name: Build with Maven
      run: mvn clean install -Dmaven.test.failure.ignore=true