name: GitHub-Actions-Chattery
on: [pull_request_target, push]
jobs:
  chattery:
    name: chattery
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is automatically triggered by ${{github.event_name}}"
      - name: post comment
        uses: lukejacksonn/chattery@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}