name: Java 17 and Maven JUnit Test

on:
  push:
    branches: [ master, tests_feature ]
  pull_request:
    branches: [ master, tests_feature ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
      
    - name: Run JUnit Tests
      run: mvn test --file pom.xml