name: Greetings
on: [pull_request_target, issues, push]
jobs:
  seend_first_greeting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
        issue-message: "Your issue will be reviewed soon."
        pr-message: "Thanks for your first pull request! Keep it up."
