name: Building project

on:
  push:
    branches: [ master, tests_feature ]
  pull_request:
    branches: [ master, tests_feature ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: '12'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Spring Boot Tests
      run: mvn spring-boot:run --file pom.xml &
    - name: Wait for Spring Boot Application to start
      run: sleep 15s
    - name: Run Spring Boot Integration Tests
      run: mvn integration-test --file pom.xml