name: GitHub-Actions-Comment-Issue
on:
  issues:
    types: [opened]

jobs:
  comment_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting! Your issue will be reviewed.'
            })