name: "Issue Labeler"
on:
  issues:
    types:
      - opened
      - reopened
      - edited

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: github/issue-labeler@v2.5 #May not be the latest version
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
        include-title: 1